name: CI

on:
  workflow_dispatch:
    inputs:
      dev:
        type: boolean
        description: "DEV"
        default: True

      test:
        type: boolean
        description: "TEST"
        default: True

      stage:
        type: boolean
        description: "STAGE"
        default: True

      prod:
        type: boolean
        description: "PROD"
        default: True

      app_version:
        description: 'Version'
        required: True
        type: choice
        default: '1.0.0'
        options:
        - '1.0.0'
        - '1.0.1'
        - '1.0.2'
        
        
