name: CI

on:
  workflow_dispatch:
    inputs:
      dev:
        type: boolean
        description: "DEV"
        default: True

      test:
        type: boolean
        description: "TEST"
        default: True

      stage:
        type: boolean
        description: "STAGE"
        default: True

      prod:
        type: boolean
        description: "PROD"
        default: True

      app_version:
        description: "Version"
        required: True
        type: choice
        default: '1.0.0'
        options:
        - '1.0.0'
        - '1.0.1'
        - '1.0.2'

jobs:
  BuildApp:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
        - name: build frontend app
          run: echo building frontend app
          
        - name: unit tests frontend
          run: echo running unit tests for frontend app
  
  BuildBackendApp:
    name: Build Backend App
    runs-on: ubuntu-latest
    steps:
        - name: build backend app
          run: echo building backend app
            
        - name: unit tests backend
          run: echo running unit tests for backend app
  
  DeployDev:
    name: Deploy to DEV environment
    runs-on: ubuntu-latest
    steps:
      - name: deploy frontend app to DEV
        run: echo deploying frontend app to DEV
        
