name: CI

on:
  workflow_dispatch:
    inputs:
      dev:
        type: boolean
        description: "DEV"
        default: True

      test:
        type: boolean
        description: "TEST"
        default: True

      stage:
        type: boolean
        description: "STAGE"
        default: True

      prod:
        type: boolean
        description: "PROD"
        default: True

      app_version:
        description: "Version"
        required: True
        type: choice
        default: '1.0.0'
        options:
        - '1.0.0'
        - '1.0.1'
        - '1.0.2'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Input
        run: |
          echo "Deployment to DEV: ${{ github.event.inputs.boolean }}" / ${{ inputs.dev }} 
          echo "Deployment to TEST: ${{ github.event.inputs.boolean }}" / ${{ inputs.test }} 
          echo "Deployment to STAGE: ${{ github.event.inputs.boolean }}" / ${{ inputs.stage }} 
          echo "Deployment to PROD: ${{ github.event.inputs.boolean }}" / ${{ inputs.prod }} 
          echo "App version to be deployed: ${{ github.event.inputs.choice }}" / ${{ inputs.app_version }}
