name: CI

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Environment'
        required: true
        type: string
        default: 'DEV'
      choice:
        type: choice
        description: "Environment"
        options:
        - foo
        - bar
        - baz
